### ISSUE TITLE
Controller Test

### ISSUE THREAD

**Issue by bilan-claudiu** [bilan-claudiu/SlaviciApp#10]
Testeaza te rog si controller-ele noi adaugate pe branch-ul bilan [ver1.6 si ver1.7]:
- English
- Promotie
- Confani
- User

**Comment by gratianmoise** [comment]
Pe langa ce m-ai rugat am testat si: 

- Tempmedie
- Tempmedii
- Universitati

De fapt am testat tot de la A la Z si am gasit aceste erori
[Corecturi SlaviciApp.docx](https://github.com/bilan-claudiu/SlaviciApp/files/6173375/Corecturi.SlaviciApp.docx)
!
