### ISSUE TITLE
Test controllers 

### ISSUE THREAD

**Issue by bilan-claudiu** [bilan-claudiu/SlaviciApp#2]
please test controllers from bilan branch ( with Postman).Thanks :)

**Comment by gratianmoise** [comment]
[Erori SlaviciApp.xlsx](https://github.com/bilan-claudiu/SlaviciApp/files/6070058/Erori.SlaviciApp.xlsx)

**Comment by gratianmoise** [comment]
am testat controlerele din aplicatie!
